### ISSUE TITLE
User receives emails in French when her Accept-language header prefers English

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-auth-mailer#30] opened 2015-03-10 16:56 UTC
E.g., `en,fr;q=0.7,en-US;q=0.3` results in an English UI on the content server, but a French email.

You can reproduce be ordering your languages in Firefox like:

![screen shot 2015-03-10 at 9 55 15 am](https://cloud.githubusercontent.com/assets/2365255/6580136/ab702b32-c70b-11e4-8ed1-2d3debdd1b17.png)

**Comment by chilts** [comment] 2015-04-27 01:31
I've managed to reproduce something which shows where this is being converted. It's inside here : https://github.com/mozilla/fxa-auth-mailer/blob/master/translator.js#L41-L45

Output of `acceptLanguage`, `languages` and `best` (once we have them) shows this clearly I reckon:

* acceptLanguage = en,fr;q=0.7,en-us;q=0.3
* languages = [ { lang: 'en', quality: 1 }, { lang: 'fr', quality: 0.7 }, { lang: 'en-us', quality: 0.3 } ]
* best = 'fr'

So something inside `i18n.normalizeLanguage(i18n.bestLanguage(languages, supportedLanguages, 'en-US'))` ... in fact it's actually `i18n.bestLanguage(...)` which is returning the `fr`, then the `i18n.normalizeLanguage(...)` is also just returnin that.

In my config, and I'm guessing the prod ones too, I have the following 'de', 'en-US', 'es' but no `en`. I dunno yet what `i18n.bestLanguage()` does yet but it seems to choose the `fr` over converting the `en` to `en-US`. (I dunno what it's supposed to do and whether it should do that.) I'll go look over there next.

**Comment by chilts** [comment] 2015-04-27 01:34
Will this be fixed (in the general case) with https://github.com/mozilla/fxa-auth-mailer/pull/40 ? Perhaps it'll be fine for just `en` but not if someone had two other languages set (non-default).

**Comment by rfk** [comment] 2015-04-27 02:55
> it seems to choose the fr over converting the en to en-US

I won't be surprised if this turns out to be "correct" behaviour per some spec somewhere...

**Comment by chilts** [comment] 2015-04-27 03:06
Yeah, I'll take a look or maybe @zaach knows.

**Comment by chilts** [comment] 2015-04-27 08:43
Inside `i18n-abide` it'll definitely map (for example) `en-US` onto `en`, but it doesn't do the other way around. In which case ... `fr` is the correct result according the the current implementation over there. I guess it makes sense that you can go from `language-region` to `language`.

Of course, if we're adding `en` to the set of supported languages, then this will match fine. Perhaps this is the bug all along which is being fixed anyway.

Not sure what's next here. It seems correct to me ... assuming `i18n-abide` is also correct. :)

**Comment by zaach** [comment] 2015-04-27 22:32
@chilts Yes, your diagnosis seems right to me. When `en` is flipped to be the default the user will see English as expected. #40 will fix it.

**Comment by chilts** [comment] 2015-04-27 22:38
@zaach. Thanks. I guess we could close this, any objections?

**Comment by chilts** [comment] 2015-04-27 22:38
I guess it still doesn't tell us why the user was shown the page in English but the email in French.

**Comment by chilts** [comment] 2015-04-27 22:39
Does the content server have a 'en' default?

**Comment by zaach** [comment] 2015-04-27 22:40
Yep.

**Comment by chilts** [comment] 2015-04-27 22:40
Ah, right cool. So we're all good. Closing since #40 will then make this the same as the content server. We should be good then.

**Closed by chilts** 2015-04-27 22:40 UTC
Labels: waffle:in progress

**Comment by chilts** [comment] 2015-04-29 02:43
Just some confirmation: now that #40 has been merged, `i18n.bestLanguage(...)` now returns `en` as the preferred language.
